version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: compile_and_run
          command: apt-get update && apt-get install make && make test
