version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
  dependencies:
    pre:
      - sudo apt-get update; sudo apt-get install make
    steps:
      - checkout
      - run:
          name: compile_and_run
          command: make test
