version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: install make
          command: sudo apt-get update & sudo apt-get install make

      - run:
          name: compile_and_run
          command: make test
